services:
  db:
    image: postgres:latest
    container_name: videoflix_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - videoflix_network

  redis:
    image: redis:alpine
    container_name: videoflix_redis
    ports:
      - "6379:6379"
    networks:
      - videoflix_network

  web:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: videoflix_backend
    command: ./backend.entrypoint.sh
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - videoflix_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  videoflix_network:
    driver: bridge
