version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: videoflix_database_prod
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-your_database_name}
      POSTGRES_USER: ${DATABASE_USER:-your_database_user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-your_database_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - videoflix_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: videoflix_redis_prod
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - videoflix_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: videoflix_backend_prod
    restart: always
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_NAME=${DATABASE_NAME:-your_database_name}
      - DATABASE_USER=${DATABASE_USER:-your_database_user}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-your_database_password}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost}
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS:-True}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - media_data:/app/media
      - static_data:/app/staticfiles
    networks:
      - videoflix_network
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3

  worker:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: videoflix_worker_prod
    restart: always
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_NAME=${DATABASE_NAME:-your_database_name}
      - DATABASE_USER=${DATABASE_USER:-your_database_user}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-your_database_password}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost}
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS:-True}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - media_data:/app/media
    networks:
      - videoflix_network
    command: python manage.py rqworker default

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_data:/app/staticfiles
      - media_data:/app/media
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - videoflix_network

volumes:
  postgres_data:
  redis_data:
  media_data:
  static_data:

networks:
  videoflix_network:
    driver: bridge