services:

  db:
    image: postgres:latest
    container_name: videoflix_database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: videoflix_redis
    volumes:
      - redis_data:/data

  maildev:
    image: maildev/maildev:latest
    container_name: videoflix_maildev
    ports:
      - "1080:1080"  
      - "1025:1025"  
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025

  web:
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: videoflix-backend:latest
    env_file: .env
    container_name: videoflix_backend
    volumes:
      - videoflix_media:/app/media
      - videoflix_static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - maildev
    command: ./backend.entrypoint.sh

  worker:
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: videoflix-backend:latest
    env_file: .env
    container_name: videoflix_worker
    volumes:
      - videoflix_media:/app/media
      - videoflix_static:/app/static
    depends_on:
      - db
      - redis
      - web
    command: ./entrypoint.worker.sh




volumes:
  postgres_data:
  redis_data:
  videoflix_media:
  videoflix_static:
